In [6]:
import numpy as np

In [7]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [25]:
#get a specific elememt r,c
a[1,5]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [11]:
#get a specific row 
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
#get a specific column
a[:,2]

array([ 3, 10])

In [15]:
#Getting a little fancy [startindex:endindex:stepindex]
a[0, 1:-1:2]  #row, column, stop before, increment 

array([2, 4, 6])

In [26]:
a[1,5] = 20 #replace element
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [29]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [31]:
#get a specific  element (work outside in)
b[0,1,1]

np.int64(4)

In [32]:
#replace 
b[:,1:] = [[9,9,9],[8,8]]
#not possible since not same number of elements

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.