In [4]:
import numpy as np 
#alll 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# all 1s is matrix
np.ones((4,2,2), dtype = "int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [9]:
#any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [10]:
#any other  (fill_line)
a = ([2,3],[3,4])
np.full_like(a,4)

array([[4, 4],
       [4, 4]])

In [13]:
#random decimal numbers
np.random.rand(4,2)
#4 rows 2 col

array([[0.99847215, 0.53533167],
       [0.01486285, 0.87773796],
       [0.40685416, 0.64677238],
       [0.78122989, 0.39297613]])

In [16]:
#random integer values
np.random.randint(-4,7 ,size=(3,3))

array([[ 1,  1, -1],
       [ 5,  6, -3],
       [ 4,  3,  6]], dtype=int32)

In [19]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis =0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [33]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9 
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
## be careful when copying arrays
a = np.array([1,2,3])
b = a #b a=b.copy()
b[0] = 100 #it changes the content also # to prevent use.copy
print(a)

[100   2   3]
