In [2]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
a + 2

array([3, 4, 5, 6])

In [5]:
a - 2

array([-1,  0,  1,  2])

In [6]:
a*2

array([2, 4, 6, 8])

In [8]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [11]:
a +=2
print(a)

[ 7  8  9 10]


In [14]:
b = np.array([1,0,1,0])
a + b

array([ 8,  8, 10, 10])

In [16]:
a ** 2

array([ 49,  64,  81, 100])

In [18]:
#take the sin
np.sin(a) #to apply sin

array([ 0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

Linear Algebra

In [ ]:
#linear algebra
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b) #matrix multiplication

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [28]:
#find determinate
c =np.identity(3)
np.linalg.det(c)

np.float64(1.0)

In [ ]:
#other ways it can be used in linear algra and using numpy library

Statistics

In [30]:
stats = ([[1,2,3] ,[4,5,6]])

stats

[[1, 2, 3], [4, 5, 6]]

In [32]:
np.min(stats,axis = 1)


array([1, 4])

In [34]:
np.max(stats)

np.int64(6)

In [36]:
np.max(stats, axis =1)

array([3, 6])

In [37]:
np.sum(stats,axis=0)

array([5, 7, 9])