Miscellaneous

In [ ]:
#load file into data
import numpy as np

data = np.genfromtxt("data.txt", delimiter=",")
print(data) #its float you can also tell it to become integer type


[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   6.   4.   3.   4.   5.   6.   7.   0.
   11.  12.   5.   6.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]


##### BOOLEAN MARKING AND ADVANCED INDEXING

In [9]:
data > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [12]:
data[data >50]

array([196.,  75., 766.,  75., 999.,  78.,  76.,  88.])

In [16]:
## you can index with the list in NumPy

a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [18]:
np.any(data >50, axis=0)

array([False, False, False, False,  True,  True, False, False,  True,
       False, False, False, False, False, False, False,  True,  True])

In [ ]:
((data > 50) & (data <100))
#not ~ 
# and &


array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])