In [1]:
import numpy as np

In [14]:
a = np.array([1,2,3] , dtype = "int16")
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
#get dimension
a.ndim

1

In [8]:
#get shape
b.shape

(2, 3)

In [15]:
#get type 
a.dtype  # we chaneg type as shown in first cell

dtype('int16')

In [23]:
#get size
a.itemsize
b.itemsize

8

In [21]:
#get total size 
a.nbytes

6